/**

 * Project Name : Project Management Application 

 * @company YMSLI

 * @author  Harshul Singla

 * @date    March 16,2022

 * Copyright (c) 2022, Yamaha Motor Solutions (INDIA) Pvt Ltd.

 * 

 * Description

 * ----------------------------------------------------------------------------------- 

 * Project : Pojo for Project

 * -----------------------------------------------------------------------------------

 */
package com.projectmanagement.model.dao;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.*;

import lombok.*;

@Data
@AllArgsConstructor
@Entity
@Table(name="project_table")
public class Project {
	
	/**
	 * 
	 * Fields
	 * 
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer projectId;
	private String projectName;
	private Date startDate;
	private Date endDate;
	private String status;
	private String clientName;
	
	@ManyToMany
	@JoinTable(name="project_user", 
	joinColumns = @JoinColumn(name="pid_fk"),
	inverseJoinColumns =@JoinColumn(name="uid_fk"))
	private List<User> users = new ArrayList<>();

	/**
	 * Default Constructor
	 */
	public Project() {
		super();
	}
	
	/**
	 * Constructor having all fields excluding ID(autogenerated)
	 * @param projectName
	 * @param startDate
	 * @param endDate
	 * @param status
	 * @param clientName
	 * @param users
	 */
	public Project(String projectName, Date startDate, Date endDate, String status, String clientName,
			List<User> users) {
		super();
		this.projectName = projectName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.status = status;
		this.clientName = clientName;
		this.users = users;
	}
	
	/**
	 * method to print project information
	 */
	@Override
	public String toString() {
		return "Project [projectId=" + projectId + ", projectName=" + projectName + ", startDate=" + startDate
				+ ", endDate=" + endDate + ", status=" + status + ", clientName=" + clientName + ", users=" + users
				+ "]";
	}
	
}
