/**

 * Project Name : Project Management Application 

 * @company YMSLI

 * @author  Harshul Singla

 * @date    March 16,2022

 * Copyright (c) 2022, Yamaha Motor Solutions (INDIA) Pvt Ltd.

 * 

 * Description

 * ----------------------------------------------------------------------------------- 

 * User : Pojo for User

 * -----------------------------------------------------------------------------------

 */
package com.projectmanagement.model.dao;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
/**
 * 
 *Fields
 *
 */
@Data
@AllArgsConstructor
@Entity
@Table(name="user_table")
public class User {
	@Id @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer userId;
	private String userName;
	private String password;
	private String profile;
	
	@ManyToMany(mappedBy = "users")
	private List<Project> projects = new ArrayList<>();	
	
	/**
	 * 
	 * Default Constructor
	 * 
	 */
	public User() {
		super();
	}

	/**
	 * method to print User information
	 */
	@Override
	public String toString() {
		return "User [userId=" + userId + ", userName=" + userName + "]";
	}

	/**
	 * Constructor having all fields excludinf ID(autogenerated)
	 * @param userName
	 * @param profile
	 * @param password
	 */
	public User(String userName, String profile, String password) {
		super();
		this.userName = userName;
		this.profile = profile;
		this.password = password;
	}

	
}
